name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  deploy-dns:
    name: Deploy DNS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        run: terraform init
        working-directory: ./src

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./src

  deploy-site:
    name: Deploy Site
    runs-on: ubuntu-latest
    needs: deploy-dns
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        run: terraform init
        working-directory: ./src

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="domain_enabled=true"
        working-directory: ./src